/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tictactoe;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TicTacoe extends javax.swing.JFrame {
    static int count=0;
    /**
     * Creates new form TicTacoe
     */
    public TicTacoe() {
        initComponents();
        setTitle("TicTacToeGame");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 204));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 255, 204));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 204));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 255, 204));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 204));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 255, 204));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 255, 204));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setBackground(Color.GREEN);
        jButton3.setLabel("*");
        if(jButton1.getBackground().equals(Color.GREEN)){
            jButton2.setBackground(Color.GREEN);
            jButton2.setLabel("0");
        }else if(jButton2.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else if(jButton6.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton7.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton6.setBackground(Color.GREEN);
            jButton6.setLabel("0");
        }else {
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
        checkWin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBackground(Color.GREEN);
        jButton1.setLabel("*");
        if(jButton2.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else if(jButton3.getBackground().equals(Color.GREEN)){
            jButton2.setBackground(Color.GREEN);
            jButton2.setLabel("0");
        }else if(jButton4.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton7.getBackground().equals(Color.GREEN)){
            jButton4.setBackground(Color.GREEN);
            jButton4.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
        else{
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
        checkWin();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setBackground(Color.GREEN);
        jButton2.setLabel("*");
        if(jButton1.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else if(jButton3.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton8.setBackground(Color.GREEN);
            jButton8.setLabel("0");
        }else if(jButton8.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else{
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
        checkWin();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jButton4.setBackground(Color.GREEN);
         jButton4.setLabel("*");
         if(jButton1.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton6.setBackground(Color.GREEN);
            jButton6.setLabel("0");
        }else if(jButton6.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else if(jButton7.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else{
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
         checkWin();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         jButton5.setBackground(Color.GREEN);
         jButton5.setLabel("*");
         if(jButton1.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton2.getBackground().equals(Color.GREEN)){
            jButton8.setBackground(Color.GREEN);
            jButton8.setLabel("0");
        }else if(jButton3.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else if(jButton4.getBackground().equals(Color.GREEN)){
            jButton6.setBackground(Color.GREEN);
            jButton6.setLabel("0");
        }else if(jButton6.getBackground().equals(Color.GREEN)){
            jButton4.setBackground(Color.GREEN);
            jButton4.setLabel("0");
        }else if(jButton7.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else if(jButton8.getBackground().equals(Color.GREEN)){
            jButton2.setBackground(Color.GREEN);
            jButton2.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else{
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }
         checkWin();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jButton6.setBackground(Color.GREEN);
         jButton6.setLabel("*");
         if(jButton3.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton4.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton4.setBackground(Color.GREEN);
            jButton4.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else{
             jButton5.setBackground(Color.GREEN);
             jButton5.setLabel("0");
        }
         checkWin();
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         jButton7.setBackground(Color.GREEN);
         jButton7.setLabel("*");
         if(jButton1.getBackground().equals(Color.GREEN)){
            jButton4.setBackground(Color.GREEN);
            jButton4.setLabel("0");
        }else if(jButton3.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else if(jButton4.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else if(jButton8.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton8.setBackground(Color.GREEN);
            jButton8.setLabel("0");
        }else{
             jButton5.setBackground(Color.GREEN);
             jButton5.setLabel("0");
        
        }
         checkWin();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         jButton8.setBackground(Color.GREEN);
         jButton8.setLabel("*");
         if(jButton2.getBackground().equals(Color.GREEN)){
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }else if(jButton5.getBackground().equals(Color.GREEN)){
            jButton2.setBackground(Color.GREEN);
            jButton2.setLabel("0");
        }else if(jButton7.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else if(jButton9.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else{
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
         checkWin();
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         jButton9.setBackground(Color.GREEN);
         jButton9.setLabel("*");
          if(jButton1.getBackground().equals(Color.GREEN)){
            jButton9.setBackground(Color.GREEN);
            jButton9.setLabel("0");
        }else  if(jButton3.getBackground().equals(Color.GREEN)){
            jButton6.setBackground(Color.GREEN);
            jButton6.setLabel("0");
        }else  if(jButton5.getBackground().equals(Color.GREEN)){
            jButton1.setBackground(Color.GREEN);
            jButton1.setLabel("0");
        }else  if(jButton6.getBackground().equals(Color.GREEN)){
            jButton3.setBackground(Color.GREEN);
            jButton3.setLabel("0");
        }else  if(jButton7.getBackground().equals(Color.GREEN)){
            jButton8.setBackground(Color.GREEN);
            jButton8.setLabel("0");
        }else  if(jButton8.getBackground().equals(Color.GREEN)){
            jButton7.setBackground(Color.GREEN);
            jButton7.setLabel("0");
        }else {
            jButton5.setBackground(Color.GREEN);
            jButton5.setLabel("0");
        }
          checkWin();
    }//GEN-LAST:event_jButton9ActionPerformed

    void checkWin(){
        
        count++;
        if(jButton1.getLabel().equals("*")){
            if(jButton2.getLabel().equals("*")){
                if(jButton3.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
         if(jButton1.getLabel().equals("*")){
            if(jButton4.getLabel().equals("*")){
                if(jButton7.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
          if(jButton3.getLabel().equals("*")){
            if(jButton6.getLabel().equals("*")){
                if(jButton9.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
           if(jButton7.getLabel().equals("*")){
            if(jButton8.getLabel().equals("*")){
                if(jButton9.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
            if(jButton1.getLabel().equals("*")){
            if(jButton5.getLabel().equals("*")){
                if(jButton9.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
             if(jButton3.getLabel().equals("*")){
            if(jButton5.getLabel().equals("*")){
                if(jButton7.getLabel().equals("*")){
                    JOptionPane. showMessageDialog(null, 
                                  "ongratulations! You won the game!!!!!!!"
                                  
                                 ); 
            }
            }
        }
        
        if(count==5){
             JOptionPane.showMessageDialog(null, 
                                  "Draw !!!!!!!"
                                  
                                 ); 
             this.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
